package com.ganesh.springapi.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@Getter
@Setter

public class Product {


    private int id;
    private String title;
    private String description;
    private double price;
    private String category;
    private String image;

    // Constructors, getters, and setters can be generated by Lombok annotations
    // or manually defined if needed


    @SpringBootApplication
    public static class SpringApiApplication {

        public static void main(String[] args) {
            SpringApplication.run(SpringApiApplication.class, args);
        }


    }
}
